# Generated by Django 6.0.1 on 2026-01-18 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
                ('scheduled_time', models.TimeField()),
                ('actual_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('TAKEN', 'Taken'), ('MISSED', 'Missed'), ('SKIPPED', 'Skipped'), ('DELAYED', 'Delayed')], max_length=20)),
                ('dosage_taken', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'medication_logs',
                'ordering': ['-scheduled_date', '-scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='MedicationRefill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_date', models.DateField(auto_now_add=True)),
                ('quantity', models.PositiveIntegerField()),
                ('pharmacy_name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'medication_refills',
                'ordering': ['-requested_date'],
            },
        ),
        migrations.CreateModel(
            name='MedicationReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('PUSH', 'Push Notification'), ('EMAIL', 'Email'), ('SMS', 'SMS')], max_length=20)),
                ('reminder_minutes_before', models.PositiveIntegerField(default=15, help_text='Minutes before scheduled time to send reminder')),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'medication_reminders',
            },
        ),
        migrations.CreateModel(
            name='MedicationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(help_text='Time to take medication')),
                ('dosage_count', models.PositiveIntegerField(default=1, help_text='Number of tablets/ml to take')),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'medication_schedules',
                'ordering': ['time'],
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Medication name', max_length=255)),
                ('generic_name', models.CharField(blank=True, max_length=255)),
                ('form', models.CharField(choices=[('TABLET', 'Tablet'), ('CAPSULE', 'Capsule'), ('SYRUP', 'Syrup'), ('INJECTION', 'Injection'), ('DROPS', 'Drops'), ('INHALER', 'Inhaler'), ('OINTMENT', 'Ointment'), ('CREAM', 'Cream'), ('OTHER', 'Other')], max_length=50)),
                ('dosage', models.CharField(help_text='e.g., 500mg, 10ml', max_length=100)),
                ('frequency', models.CharField(choices=[('ONCE_DAILY', 'Once a day'), ('TWICE_DAILY', 'Twice a day'), ('THRICE_DAILY', 'Three times a day'), ('FOUR_TIMES_DAILY', 'Four times a day'), ('EVERY_4_HOURS', 'Every 4 hours'), ('EVERY_6_HOURS', 'Every 6 hours'), ('EVERY_8_HOURS', 'Every 8 hours'), ('EVERY_12_HOURS', 'Every 12 hours'), ('AS_NEEDED', 'As needed'), ('WEEKLY', 'Once a week'), ('CUSTOM', 'Custom schedule')], max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('duration_days', models.PositiveIntegerField(blank=True, null=True)),
                ('instructions', models.TextField(blank=True, help_text='Special instructions (before/after meals, etc.)')),
                ('side_effects', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_refill_needed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medications', to='appointments.appointment')),
            ],
            options={
                'db_table': 'medications',
                'ordering': ['-created_at'],
            },
        ),
    ]
