# Generated by Django 6.0.1 on 2026-01-18 03:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0002_initial'),
        ('medications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='patient',
            field=models.ForeignKey(limit_choices_to={'role': 'PATIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='medications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medication',
            name='prescribed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescribed_medications', to='doctor.doctorprofile'),
        ),
        migrations.AddField(
            model_name='medicationlog',
            name='medication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='medications.medication'),
        ),
        migrations.AddField(
            model_name='medicationrefill',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_refills', to='doctor.doctorprofile'),
        ),
        migrations.AddField(
            model_name='medicationrefill',
            name='medication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refills', to='medications.medication'),
        ),
        migrations.AddField(
            model_name='medicationrefill',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_refills', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicationreminder',
            name='medication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='medications.medication'),
        ),
        migrations.AddField(
            model_name='medicationschedule',
            name='medication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='medications.medication'),
        ),
        migrations.AddField(
            model_name='medicationreminder',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='medications.medicationschedule'),
        ),
        migrations.AddField(
            model_name='medicationlog',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='medications.medicationschedule'),
        ),
        migrations.AddIndex(
            model_name='medication',
            index=models.Index(fields=['patient', 'is_active'], name='medications_patient_341b47_idx'),
        ),
        migrations.AddIndex(
            model_name='medication',
            index=models.Index(fields=['start_date', 'end_date'], name='medications_start_d_8d0395_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='medicationschedule',
            unique_together={('medication', 'time')},
        ),
        migrations.AddIndex(
            model_name='medicationlog',
            index=models.Index(fields=['medication', 'scheduled_date'], name='medication__medicat_fc636d_idx'),
        ),
        migrations.AddIndex(
            model_name='medicationlog',
            index=models.Index(fields=['status', 'scheduled_date'], name='medication__status_dd3edd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='medicationlog',
            unique_together={('medication', 'scheduled_date', 'scheduled_time')},
        ),
    ]
