# Generated by Django 6.0.5 on 2026-05-21 03:45

import django.db.models.deletion
import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('VIEW', 'Viewed'), ('DOWNLOAD', 'Downloaded'), ('SHARE', 'Shared'), ('DELETE', 'Deleted'), ('UPDATE', 'Updated')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'document_access_logs',
                'ordering': ['-accessed_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shared_with_email', models.EmailField(blank=True, max_length=254)),
                ('shared_with_phone', models.CharField(blank=True, max_length=15)),
                ('share_method', models.CharField(choices=[('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp'), ('LINK', 'Shareable Link')], max_length=20)),
                ('share_token', models.CharField(blank=True, max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('accessed_count', models.PositiveIntegerField(default=0)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'document_shares',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('LAB_REPORT', 'Lab Report'), ('PRESCRIPTION', 'Prescription'), ('SCAN', 'Scan/X-ray'), ('MRI', 'MRI'), ('CT_SCAN', 'CT Scan'), ('BLOOD_TEST', 'Blood Test'), ('VACCINATION', 'Vaccination Record'), ('DISCHARGE_SUMMARY', 'Discharge Summary'), ('MEDICAL_CERTIFICATE', 'Medical Certificate'), ('OTHER', 'Other')], max_length=50)),
                ('file', models.FileField(upload_to=documents.models.medical_document_upload_path)),
                ('file_size', models.PositiveIntegerField(editable=False, help_text='File size in bytes')),
                ('file_type', models.CharField(blank=True, editable=False, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('document_date', models.DateField(blank=True, help_text='Date when the document was created/issued', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'medical_documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('VIEWED', 'Viewed by Patient')], default='DRAFT', max_length=20)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'prescriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionMedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=200)),
                ('dosage', models.CharField(help_text='e.g. 500mg', max_length=100)),
                ('frequency', models.CharField(help_text='e.g. Twice daily', max_length=100)),
                ('duration', models.CharField(help_text='e.g. 7 days', max_length=100)),
                ('instructions', models.TextField(blank=True, help_text='e.g. Take after food')),
            ],
            options={
                'db_table': 'prescription_medications',
            },
        ),
        migrations.CreateModel(
            name='AppointmentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_documents', to='appointments.appointment')),
            ],
        ),
    ]
