# Generated by Django 6.0.5 on 2026-05-21 03:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0002_initial'),
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documentaccesslog',
            name='accessed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_accesses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentshare',
            name='shared_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_shares', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='patient',
            field=models.ForeignKey(limit_choices_to={'role': 'PATIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='medical_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='shared_with_doctors',
            field=models.ManyToManyField(blank=True, related_name='accessible_documents', to='doctor.doctorprofile'),
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentshare',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='documents.medicaldocument'),
        ),
        migrations.AddField(
            model_name='documentaccesslog',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='documents.medicaldocument'),
        ),
        migrations.AddField(
            model_name='appointmentdocument',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_links', to='documents.medicaldocument'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='doctor.doctorprofile'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(limit_choices_to={'role': 'PATIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prescription',
            name='related_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='documents.medicaldocument'),
        ),
        migrations.AddField(
            model_name='prescriptionmedication',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='documents.prescription'),
        ),
        migrations.AddIndex(
            model_name='medicaldocument',
            index=models.Index(fields=['patient', 'category'], name='medical_doc_patient_ddd1e9_idx'),
        ),
        migrations.AddIndex(
            model_name='medicaldocument',
            index=models.Index(fields=['created_at'], name='medical_doc_created_a3414c_idx'),
        ),
        migrations.AddIndex(
            model_name='documentshare',
            index=models.Index(fields=['share_token'], name='document_sh_share_t_17ea28_idx'),
        ),
        migrations.AddIndex(
            model_name='documentshare',
            index=models.Index(fields=['expires_at'], name='document_sh_expires_a17740_idx'),
        ),
        migrations.AddIndex(
            model_name='documentaccesslog',
            index=models.Index(fields=['document', 'accessed_at'], name='document_ac_documen_b365a5_idx'),
        ),
        migrations.AddIndex(
            model_name='documentaccesslog',
            index=models.Index(fields=['accessed_by', 'accessed_at'], name='document_ac_accesse_2c7482_idx'),
        ),
        migrations.AddIndex(
            model_name='appointmentdocument',
            index=models.Index(fields=['appointment'], name='documents_a_appoint_18c238_idx'),
        ),
        migrations.AddIndex(
            model_name='appointmentdocument',
            index=models.Index(fields=['document'], name='documents_a_documen_483ac6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='appointmentdocument',
            unique_together={('appointment', 'document')},
        ),
    ]
