# Generated by Django 5.0.14 on 2026-02-22 07:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_documentaccesslog_id_alter_documentshare_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicaldocument',
            name='is_shared_with_doctor',
        ),
        migrations.AlterField(
            model_name='documentaccesslog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='documentshare',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='medicaldocument',
            name='file_size',
            field=models.PositiveIntegerField(editable=False, help_text='File size in bytes'),
        ),
        migrations.AlterField(
            model_name='medicaldocument',
            name='file_type',
            field=models.CharField(blank=True, editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='medicaldocument',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='documentshare',
            index=models.Index(fields=['share_token'], name='document_sh_share_t_17ea28_idx'),
        ),
        migrations.AddIndex(
            model_name='documentshare',
            index=models.Index(fields=['expires_at'], name='document_sh_expires_a17740_idx'),
        ),
    ]
