# Generated by Django 5.0.14 on 2026-03-01 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_alter_appointment_unique_together_and_more'),
        ('documents', '0004_remove_medicaldocument_is_shared_with_doctor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_documents', to='appointments.appointment')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_links', to='documents.medicaldocument')),
            ],
            options={
                'indexes': [models.Index(fields=['appointment'], name='documents_a_appoint_18c238_idx'), models.Index(fields=['document'], name='documents_a_documen_483ac6_idx')],
                'unique_together': {('appointment', 'document')},
            },
        ),
    ]
