# Generated by Django 6.0.5 on 2026-05-21 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('slot_duration', models.PositiveIntegerField(default=30, help_text='Appointment slot duration in minutes')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'doctor_availability',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(choices=[('CARDIOLOGY', 'Cardiology'), ('DERMATOLOGY', 'Dermatology'), ('NEUROLOGY', 'Neurology'), ('PEDIATRICS', 'Pediatrics'), ('ORTHOPEDICS', 'Orthopedics'), ('PSYCHIATRY', 'Psychiatry'), ('GENERAL', 'General Medicine'), ('ENT', 'ENT Specialist'), ('GYNECOLOGY', 'Gynecology'), ('ONCOLOGY', 'Oncology'), ('OTHER', 'Other')], max_length=50)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('qualification', models.CharField(blank=True, max_length=200)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('consultation_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bio', models.TextField(blank=True, help_text='Brief description about the doctor')),
                ('clinic_address', models.TextField(blank=True)),
                ('is_available', models.BooleanField(default=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='doctor_photos/')),
                ('license_photo', models.ImageField(blank=True, null=True, upload_to='doctor_licenses/')),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'doctor_profiles',
                'ordering': ['-rating', '-experience_years'],
            },
        ),
        migrations.CreateModel(
            name='DoctorReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Rating from 1 to 5')),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'doctor_reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
