# Generated by Django 6.0.5 on 2026-05-21 03:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'DOCTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='verified_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'ADMIN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_doctors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='doctor.doctorprofile'),
        ),
        migrations.AddField(
            model_name='doctorreview',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='doctor.doctorprofile'),
        ),
        migrations.AddField(
            model_name='doctorreview',
            name='patient',
            field=models.ForeignKey(limit_choices_to={'role': 'PATIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='doctorprofile',
            index=models.Index(fields=['specialization'], name='doctor_prof_special_0de2d3_idx'),
        ),
        migrations.AddIndex(
            model_name='doctorprofile',
            index=models.Index(fields=['is_available'], name='doctor_prof_is_avai_8ad711_idx'),
        ),
        migrations.AddConstraint(
            model_name='doctoravailability',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='end_time_after_start'),
        ),
        migrations.AddConstraint(
            model_name='doctoravailability',
            constraint=models.UniqueConstraint(fields=('doctor', 'day_of_week', 'start_time'), name='unique_doctor_day_start'),
        ),
        migrations.AlterUniqueTogether(
            name='doctorreview',
            unique_together={('doctor', 'patient')},
        ),
    ]
