# Generated by Django 5.0.14 on 2026-04-06 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_alter_doctoravailability_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='verification_status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='verified_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'ADMIN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_doctors', to=settings.AUTH_USER_MODEL),
        ),
    ]
