# Generated by Django 5.0.14 on 2026-04-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_remove_doctorprofile_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='license_photo',
            field=models.ImageField(blank=True, null=True, upload_to='doctor_licenses/'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='doctor_photos/'),
        ),
    ]
