# Generated by Django 5.0.14 on 2026-04-18 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_doctorprofile_license_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='total_patients',
        ),
    ]
